web/viewProjects.php

Apply alphabetical sort of areas in project management screen

---

config/permissions.php
model/dao/TaskDAO/PostgreSQLTaskDAO.php
model/dao/TaskDAO/TaskDAO.php
model/facade/TasksFacade.php
model/facade/action/GetProjectUserWeeklyHoursReportAction.php
web/services/getProjectUserWeeklyHoursReportJsonService.php
web/viewProjectDetails.php

Will show up in phpreport/web/viewProjectDetails.php?pid=<$pid>

[#240] Implement new report to list weekly work hours per user for a project

---

config/permissions.php

Urgent fix, after https://github.com/Igalia/phpreport/commit/7cc144c47c6160e054a2c8195c2b491bca9db06f

[#268] Re-add viewUsers.php to admin array, allow managing users

---

docs/user/tasks.rst
model/dao/DAOFactory.php
model/dao/TemplateDAO/PostgreSQLTemplateDAO.php
model/dao/TemplateDAO/TemplateDAO.php
model/facade/TemplatesFacade.php
model/facade/action/CreateTemplateAction.php
model/facade/action/DeleteTemplateAction.php
model/facade/action/GetUserTemplatesAction.php
model/vo/TemplateVO.php
web/js/tasks.js
web/services/createTemplatesService.php
web/services/deleteTemplatesService.php
web/services/getUserTemplatesService.php

Needs more work with phpdoc and implementing the delete feature too.

Make Template actions comply  with phpreport DB abstractions

---

web/js/tasks.js

TODO:
* Would look more good if the text is moved to the right end.

[#246] Autosave tasks, once valid

---

web/js/tasks.js
web/services/checkSessionActive.php

Can be tested by logging out from another tab by keeping the session active in the main one.

[#65] Prompt user to login again when session has expired in background

---

web/viewProjectDetails.php

Looks like this was from my part. Sorry for that, and I am merging it straightaway, as this shouldnt be in master.

Remove unnecessary debug code from viewProjects file

---

model/dao/TaskDAO/PostgreSQLTaskDAO.php
model/facade/action/GetProjectUserWeeklyHoursReportAction.php
web/services/getProjectUserWeeklyHoursReportJsonService.php

[#281] Implement better sorting on weekly hours reports, respecting year of task

---

web/js/projectDetails.js

[#266] Make the project input box still wider, no more clipping

---

config/config.php
config/permissions.php
sql/update/add-manager-user-group.sql
util/LoginManager.php
web/services/getProjectUserCustomerReportJsonService.php
web/services/getTasksFiltered.php
web/services/getUserProjectCustomerReportJsonService.php
web/userTasksReport.php
web/viewProjectDetails.php
web/viewUserDetails.php
web/viewUsers.php

[#244] Introduce new 'manager' profile, restrict 'staff' access

---

config/permissions.php
model/dao/DAOFactory.php
model/dao/UserGoalDAO/PostgreSQLUserGoalDAO.php
model/dao/UserGoalDAO/UserGoalDAO.php
model/facade/UsersFacade.php
model/facade/action/CreateUserGoalAction.php
model/facade/action/DeleteUserGoalAction.php
model/facade/action/GetPersonalSummaryByLoginDateAction.php
model/facade/action/GetUserGoalsAction.php
model/facade/action/GetWeeklyGoalSummaryAction.php
model/facade/action/UpdateUserGoalAction.php
model/vo/UserGoalVO.php
sql/update/create-user_goals-table.sql
web/js/tasks.js
web/services/createUserGoalsService.php
web/services/deleteUserGoalsService.php
web/services/getPersonalSummaryByDateService.php
web/services/getUserGoalsService.php
web/services/updateUserGoalsService.php
web/viewUsers.php

More work required to actually implement the business logic, and show up in `tasks.php` sidebar

[#243] Implement OverTime Control

---

web/js/tasks.js

[#246] Show up 'saved-task' App banner only on manually saved tasks

---

model/dao/UserGoalDAO/PostgreSQLUserGoalDAO.php
model/dao/UserGoalDAO/UserGoalDAO.php
model/facade/action/GetPersonalSummaryByLoginDateAction.php

[#243] Improve the accuracy of overtime-control functions

---

web/js/tasks.js

[#293] Fix: Template tasks may delete new tasks

---

model/dao/ProjectDAO/PostgreSQLProjectDAO.php
web/js/tasks.js
web/services/getProjectsAndCustomersForLoginService.php

Smart custom combo with 'Load all Projects' item in dropdown

---

web/viewCustomers.php

[#220] Fix strange behaviour for inline editor in viewCustomers.php

---

model/dao/ProjectDAO/PostgreSQLProjectDAO.php
model/dao/ProjectDAO/ProjectDAO.php
model/facade/ProjectsFacade.php
model/facade/action/GetFilteredCustomProjectsAction.php
web/projectsEvaluation.php
web/services/getFilteredCustomProjectsService.php
web/viewProjectDetails.php

[#186] Show up Customer field in projectsEvaluation table

---

web/js/tasks.js

[#250] Change layout of fields in the tasks screen

---

web/js/userTasksReport.js
web/services/getTasksFiltered.php

[#194] Add hours column to user tasks report

---

model/dao/ProjectDAO/PostgreSQLProjectDAO.php
web/js/tasks.js
web/services/getProjectService.php

Fix #219 
Also fix `getProject` call to return `customername` too

[#219] Show up tooltip for project names over combo box

---

model/dao/ProjectDAO/PostgreSQLProjectDAO.php
model/dao/ProjectDAO/ProjectDAO.php
model/facade/ProjectsFacade.php
model/facade/action/GetAllProjectsAction.php
web/js/tasks.js
web/projectsEvaluation.php
web/services/getProjectsService.php

The patch fix various speed and user interaction issues after PR #305. Also fixed `projectDetails` report, which was not working after PR 305

Simplify query for tasks page with a filter flag after PR: #305

---

web/viewWorkingHoursResultsReport.php

[#235] Scroll to logged in username in acc hours report

---

web/js/tasks.js

[#252] Add previous/next day buttons in Title panel header

---

model/dao/TaskDAO/PostgreSQLTaskDAO.php
model/facade/action/ExtraHoursReportAction.php
web/services/getExtraHoursReportService.php
web/viewWorkingHoursResultsReport.php

* Added Last task date column in viewWorkingHoursResultsReport.php
* getExtraHoursReportService.php includes the lastTaskDate element
* Code formatting in getExtraHoursReportService.php
Related: #357

I357 new last date column in accumulated hours report

---

web/viewUserDetails.php

* Replaced `login` field by `userLogin` combobox
* Added 'userStore` as Ext.data.Store for `userLogin`
* `userLogin` is filled with the user accounts
* `userLogin` is only enabled when the logged user has the right permissions
* Adjusted the width of the form panel
* `getUserProjectCustomerReportJsonService.php` receives the uid selected in the `userLogin`
Related issue #332

I332 Add direct access to user details for any user

---

web/auth.php
web/login.php

* auth.php pass a the `$_SERVER[REQUEST_URI]` as the `login_success_url` in the login.php redirection
* added `set_location_header_on_login_success_url()` function in  `login.php`
* `login.php` check if a `login_success_url` parameter is passed in  the `GET` or `POST` and use it as `Location` value for the redirection  on the login success
Related to the #326 issue

I326 Redirect to original URL after successful login

---

config/config.php
config/config.template
web/include/sidebar.php
web/js/tasks.js
web/js/userTasksReport.js
web/tasks.php
web/userTasksReport.php

* Added the MENU_COORDINATION config parameter
* When MENU_COORDINATION is set to FALSE, the Coordination menu in
the sidebar is hidden
Refers to #367

I367 Hide Coordination menu

---

web/js/tasks.js
web/tasks.php

Button added. Tested on a local deployment.
It will probably require some revision of the configuration files of the specific deployments, should we warn this somehow?

[#389] Add a button to fill a full holiday

---

docs/user/tasks.rst
web/js/tasks.js
web/services/getPersonalSummaryByDateService.php

This implements the agreement we met at issue #341

Improve user work summary at task panel 

---

web/js/tasks.js
web/services/getPersonalSummaryByDateService.php

Arithmetic operations were not correct. 
I've tested this code using a production database with real data and results are now the expected.

Fix arithmetic operations on the user work summary

---

web/js/tasks.js
web/services/getPersonalSummaryByDateService.php

* Changed field sort
Extra hours together. Pending Holidays to the bottom.
* New calculations over pendingHolidays.
If it is greater than a `week*currentJourney` it will show it in `day hours:minutes format` to improve readability

Small changes over the User Work Summary

---

web/js/tasks.js

After the last additions we made on this panel, information was starting to be a bit tough to read and digest.
I've added new elements as titles to group data in sections and alternated the bold, between titles and information, to improve this.

Improved readability of the user work summary

---

config/config.php
jobs/sendEmailAlertNoFill.php
jobs/sendEmailSummaryNoFill.php
templates/no_fill_critical.txt
templates/no_fill_last.txt
templates/no_fill_summary_managers.txt
templates/no_fill_warning.txt
web/services/sendEmailAlertNoFill.php

To implement what is stated in #334 
* Added configuration parameters
* Added a couple of email templates
* Initial version of the web service

Creation of a email fill in reminder web service

---

web/analysistracker-summary.php
web/calendarManagement.php
web/cityManagement.php
web/hourCompensationManagement.php
web/include/footer.php
web/include/header.php
web/include/menubar.css
web/include/menubar.php
web/iterationForm.php
web/moduleForm.php
web/projectDetails.php
web/projectsEvaluation.php
web/projectsSummary.php
web/sectionForm.php
web/settings.php
web/storyForm.php
web/taskSectionForm.php
web/taskStoryForm.php
web/tasks.php
web/userTasksReport.php
web/usersEvaluation.php
web/viewIteration.php
web/viewModule.php
web/viewProjectDetails.php
web/viewSection.php
web/viewStory.php
web/viewUserDetails.php
web/viewUsers.php
web/viewWorkingHoursResultsReport.php
web/xptracker-summary.php

Got them from the W3C validator: https://validator.w3.org/

Fix a number of HTML validation errors and warnings

---

docs/admin/installation.rst
model/dao/TaskDAO/PostgreSQLTaskDAO.php
web/auth.php
web/services/getProjectUserCustomerReportJsonService.php
web/services/getProjectUserStoryReportJsonService.php
web/services/getProjectUserWeeklyHoursReportJsonService.php
web/viewProjectDetails.php

As a highlight of these changes, we started using the `??` null coalesce operator which is new to PHP7. It shouldn't be a problem to bump the required PHP version nowadays.

Address some PHP warnings in project details report

---

config/permissions.php
web/js/projectDetails.js
web/js/projectDetailsReport.js
web/js/projectManagement.js
web/projectDetailsReport.php
web/projectsEvaluation.php
web/viewProjectDetails.php
web/viewUserDetails.php

One more step towards #401: process the project details report.
First, we had to remove the inline PHP code inside JS, then split the file in two, and rename the report in the process.

Extract JS code from viewProjectDetails.php.

---

model/dao/ExtraHourDAO/PostgreSQLExtraHourDAO.php
model/dao/TaskDAO/PostgreSQLTaskDAO.php
model/dao/UserGoalDAO/PostgreSQLUserGoalDAO.php
web/services/createTasksService.php
web/services/getOpenTaskStoriesService.php
web/services/getPersonalSummaryByDateService.php
web/services/getProjectsService.php
web/services/getUserTasksService.php
web/services/getUserTemplatesService.php

Fix mostly undefined offset/index errors in code called by the tasks page.
Related #431.

Address some PHP warnings in tasks page.

---

Dockerfile
docs/admin/docker.rst
docs/admin/index.rst
sql/create_db.sql
supervisor/supervisord.conf

Allow to create a docker image containing phpreport.

Add docker support

---

web/services/getPersonalSummaryByDateService.php

Include future holidays in user tasks summary

---

web/js/include/sessionTracker.js

Check session status on tab visibility change

---

Makefile
config/permissions.php
docs/developer/web-service-layer.rst
web/APITest.php
web/js/APITest.js

Create `web/APITest.php` to be able to try web service calls via XHR in a convenient way.

API test page

---

web/services/getSessionUser.php

It returns data of the currently logged-in user.

Add service getSessionUser.php

---

model/dao/ProjectDAO/PostgreSQLProjectDAO.php
model/dao/TaskDAO/PostgreSQLTaskDAO.php
web/services/deleteTasksService.php
web/services/updateProjectsService.php

Fix PHP warnings in task delete and project update

---

model/facade/action/ExtraHoursReportAction.php
model/facade/action/GetPendingHolidayHoursAction.php
model/facade/action/GetPersonalSummaryByLoginDateAction.php
util/LoginManager.php
web/auth.php
web/login.php
web/services/createTemplatesService.php
web/services/deleteTemplatesService.php
web/services/getAllUsersService.php
web/viewUsers.php

Most of the issues were related to accessing an index from an empty array or null variable.
Tested locally with PHP 7.4.21
Related to #431

Fix a few PHP warnings

---

model/vo/TemplateVO.php

It is not been used anymore and the property was already removed

Remove customerid leftovers from TemplateVO

---

model/dao/TemplateDAO/PostgreSQLTemplateDAO.php
model/vo/TemplateVO.php
sql/update/add-init-end-to-template-table.sql
sql/update/all.sql
web/js/tasks.js
web/services/createTemplatesService.php
web/services/getUserTemplatesService.php

Start storing init and end times to the task template.
If the task doesn't have times set, the template won't have them either.
Closes #346

Save init and end times in the task template

---

model/dao/BelongsDAO/LDAPBelongsDAO.php
model/facade/action/ExtraHoursReportAction.php
web/services/getExtraHoursReportService.php
web/services/getPendingHolidayHoursService.php

Fix PHP warnings in the accumulated hours report

---

model/facade/action/GetUserTasksByDateAction.php
model/vo/JourneyHistoryVO.php
web/services/getUserAreaHistoriesService.php
web/services/getUserCityHistoriesService.php
web/services/getUserGoalsService.php
web/services/getUserHourCostHistoriesService.php
web/services/getUserJourneyHistoriesService.php

- Fix indentation in some files
- Fix "Undefined index: sid" in some files

Minor fixes

---

model/dao/AreaHistoryDAO/PostgreSQLAreaHistoryDAO.php
model/dao/CityHistoryDAO/PostgreSQLCityHistoryDAO.php
model/dao/HourCostHistoryDAO/PostgreSQLHourCostHistoryDAO.php
model/dao/JourneyHistoryDAO/PostgreSQLJourneyHistoryDAO.php
model/dao/UserGoalDAO/PostgreSQLUserGoalDAO.php
web/services/createAreaHistoriesService.php
web/services/createCityHistoriesService.php
web/services/createHourCostHistoriesService.php
web/services/createJourneyHistoriesService.php
web/services/createUserGoalsService.php
web/services/deleteAreaHistoriesService.php
web/services/deleteCityHistoriesService.php
web/services/deleteHourCostHistoriesService.php
web/services/deleteJourneyHistoriesService.php
web/services/updateAreaHistoriesService.php
web/services/updateCityHistoriesService.php
web/services/updateHourCostHistoriesService.php
web/services/updateJourneyHistoriesService.php
web/services/updateUserGoalsService.php

Fixes:
* 'undefined variable' errors in web services layer.
* 'sizeof(): parameter must be an array' errors in DAO layer.
* 'undefined offset' errors in DAO layer.

[#431] Fix PHP warnings in user management screen.

---

web/holidayManagement.php
web/include/calendar.css
web/include/phpreport.css
web/js/holidayManagement.js
web/services/HolidayService.php
web/services/getHolidays.php
web/services/getPersonalSummaryByDateService.php

Allow to pick a user in an autocomplete dropdown to visualize the holidays from any other person.
https://user-images.githubusercontent.com/333447/140186720-0d797c26-b990-47ee-a5da-949b651d8e9f.mov
(sorry for the long PR, I tried to break it down but the whole change is a bit connected)

Add team calendar tab

---

docs/user/tasks.rst
model/facade/action/GetHolidayHoursBaseAction.php
web/holidayManagement.php
web/js/holidayManagement.js
web/js/tasks.js
web/services/getPersonalSummaryByDateService.php

Not every taken leave was really "enjoyed"/for pleasure

Rename `enjoyed` to `used` when referring to past holidays

---

model/facade/action/SyncCalendarAction.php

Change how to invite the user to the event so the event is created in the holidays calendar but also displayed in the user's personal calendar.

Fix calDav event description

---

.github/workflows/runtests.yml
README.md
composer.json

Add action to be triggered on every pull request and run the automated tests.

Add gh action to run tests

---

Makefile

Avoid trying to run on composer libs and replacing VueJs files

Ignore holiday views and vendor folder on Makefile

---

model/dao/TaskDAO/PostgreSQLTaskDAO.php
model/facade/action/GetUserProjectWorkReportAction.php
web/services/createTasksService.php
web/services/getTasksFiltered.php
web/services/getUserProjectCustomerReportJsonService.php
web/userTasksReport.php

I went through the server logs and fixed a pile of these.

Fix more PHP warnings

---

config/config.php
web/holidayManagement.php
web/holidaySummary.php
web/include/menubar.php
web/js/tasks.js

Following the new agreement, we should start using Vacation.
@jaragunde I haven't changed the project name as this would need a change in config and in the db, right? Not sure if it's worth do do it.

Rename Holiday to Vacation

---

config/config.php
docs/admin/ldap.rst
model/facade/UsersFacade.php
model/facade/action/GetAllActiveUsersAction.php
web/js/holidayManagement.js
web/services/getAllUsersService.php

- Add generic support to filter employees in `GetAllActiveUsers` façade
- Filter employees on Vacation management view

Add employees filter on Vacation Management

---

model/facade/action/GetHolidaySummaryReportAction.php
web/holidaySummary.php
web/services/HolidayService.php
web/services/getHolidaySummary.php

- Remove available days column
- Fix how to iterate through users list

Vacation Report fixes

---

web/viewUsers.php

Added a combo box that can be used to filter the list of users, it is very useful when the number of users is very high.
The interaction is not perfect, e.g. I don't like how the combo opens up automatically on focus, but the functionality is great IMO.

Add filter by users to user management screen.

---

web/js/projectManagement.js

Add a combo box to filter the list of projects.
~~TODO: the box should allow to search by customer name too, like we do in the tasks screen.~~

Project management: add project name filter.

---

web/js/tasks.js

Speed up the load of the list of tasks, by fetching them before the onReady event.
Fixes #506.

Speed up tasks page

---

model/dao/ProjectDAO/PostgreSQLProjectDAO.php
model/dao/TaskDAO/PostgreSQLTaskDAO.php
model/dao/UserDAO/PostgreSQLUserDAO.php
model/facade/action/GetProjectUserCustomerReportAction.php
model/facade/action/GetProjectUserStoryReportAction.php
web/projectsEvaluation.php
web/services/getProjectService.php
web/services/getProjectUserCustomerReportJsonService.php
web/services/getProjectUserStoryReportJsonService.php
web/services/getProjectUserWeeklyHoursReportJsonService.php
web/services/loginService.php

* Undefined index: format
* Undefined index: pid
* Undefined index: sid (twice)
* Undefined index: PHP_AUTH_USER
* Undefined offset: 0 (twice)
* Undefined variable: results (twice)
* Undefined variable: records (twice)
* Undefined variable: rows
* Undefined variable: stories
* Undefined variable: userLogin
* Undefined variable: userPassword
And other warnings derived from the above.

[#431] Fix PHP warnings.

---

web/js/tasks.js

The new, empty task that appears when no task are saved for the day feels too slow. The reason is: if the function is called before tasks have been loaded, it sets a 1-second timeout before retrying, which is too slow.
To fix the issue, we refactor the code a bit so the function is called as soon as possible, exactly when task load is done.
CC @mrobinson, this started feeling slow after landing #571 :grin:

Remove timeout for new, empty task creation.

---

web/viewUsers.php

There were problems with certain versions of Firefox.

Review panel height values in user management page.

---

web/services/HolidayService.php

Make sure we don't end up with lots of decimal places breaking the summary report table.

Round vacation summary per week

---

docs/admin/ldap.rst
docs/developer/devel-setup.rst
docs/user/reports.rst
docs/user/tasks.rst

A small update on the docs; there are still new features missing (vacation management) but at least I delete references to things we removed, do some updates/fixes and add a brief reference to the new vacation report.

Update user documentation

---

model/dao/TaskDAO/PostgreSQLTaskDAO.php
model/facade/action/GetHolidayHoursBaseAction.php
model/facade/action/GetHolidaySummaryReportAction.php
web/holidaySummary.php
web/include/report.css
web/services/getHolidaySummary.php

It shows the date when the last vacation task was updated by the user.

Add Last Update in the Vacation Summary Report

---

Dockerfile

add missing package

---

Dockerfile
supervisor/supervisord.conf

Running on the old bionic we had trouble with the PHP and UglifyJS versions, at least.

Update docker files to use latest Ubuntu LTS.

---

config/config.php
model/facade/action/SyncCalendarAction.php

Currently our username and email don't match so if these values
are different the calendar event won't be displayed in the user's
calendar.

caldav: add email for calendar user

---

config/permissions.php
web/include/form.css
web/include/menubar.php
web/js/longLeaves.js
web/longLeaves.php
web/projectDetailsReport.php

Very simple form to allow admin users to add long leaves for other users. It doesn't have validation in the front end but it uses the same logic in the back end for create tasks so it has validation there.

Add UI to create periods of long leaves

---

web/include/form.css
web/js/longLeaves.js
web/longLeaves.php
web/services/HolidayService.php
web/services/updateLongLeaves.php

After showing to the stakeholders, they said it was also important to be able to fill this data.

Add description to the long leave form

---

NEWS
config/config.php
config/config.template
docs/admin/common-problems.rst
docs/admin/installation.rst
docs/admin/upgrade.rst
docs/developer/devel-setup.rst
docs/user/index.rst
docs/user/users-management.rst

What we do here:
* Update installation docs
* Document "long leaves" ui
* Write 2.22 upgrade document
* Mark new parameters in config.php and sync with config.template

Setup release 2.22

---

model/facade/action/GetHolidaySummaryReportAction.php

In case the user was filtering the report for another year that was not the current one, the Used Hours column would be wrong because it was filtering the hours until the current day instead of the last day of the report year. This would result in a range of dates that spawns from Jan 1st of the filtered year until the current day.
We want to use the current date as end date only if we are filtering for the current year.
PS: I really tried to create tests for this but the dependencies are too coupled and would required a big refactoring that I would rather not do it now - it could be lack of skills from my side as well but from what I digged into PhpUnit and how it works, mocking static methods and classes called inside other classes is very painful, ideally we want to decouple the …

Fix Vacation Summary report Used Hours column

---

jobs/sendEmailAlertNoFill.php
jobs/sendEmailSummaryNoFill.php
model/dao/TaskDAO/PostgreSQLTaskDAO.php

- Fix how to fetch days without tasks
- Ignore users with journeys of 0 hours

Fixes in email warning

---

web/js/tasks.js

Make easier for people to skip days by having a default template they can use.

Add default Zero Hours Day template

---

.github/workflows/runtests.yml
.gitignore
api/.flake8
api/db/base_class.py
api/db/db_connection.py
api/main.py
api/models/area.py
api/models/city.py
api/models/config.py
api/models/customer.py
api/models/project.py
api/models/sector.py
api/models/timelog.py
api/models/user.py
api/pyproject.toml
api/routers/projects.py
api/schemas/project.py
api/tox.ini
docker/test.app.Dockerfile

Add black and flake8 checks and fix style issues

---

web/js/include/sessionTracker.js

Increase the session check for user convenience. 
JS also formatted on save by prettier.

Increase check for session to 1 hour

---

model/dao/DAOFactory.php
util/ConfigurationParametersManager.php

It is needed in order to use LDAP.

Revert custom DAO

---

api/migrations/versions/b7cbb5c2b970_add_task_type.py
api/models/timelog.py

This will be used in the task form and in the future we'll have a UI so admins can manage this better.

Add Task Type entity

---

frontend/src/Main.jsx
util/LoginManager.php
web/services/WebServicesFunctions.php
web/services/getTaskTypes.php

- Add silent renew for React frontend
- Check token when making api request from php, refresh if expired
- Add methods to check token status and initiate a refresh
- Auto-formatting

Add refresh token code logic

---

api/dependencies.py
api/main.py
api/routers/v1/users.py
api/schemas/user.py

- Move the AppUser to user schemas
- Add `users/me` endpoint to fetch more details about the current user, incluing the user_id that is needed in order to use other endpoints

Add users/me endpoint

---

api/models/user.py

The migration was created already on 35830895 but we missed updating the model.

Increase login column size for username

---

api/routers/v1/timelog.py
api/services/timelog.py

- Add endpoint and corresponding service method to delete a template

Add DELETE endpoint for templates

---

api/routers/v1/timelog.py
api/services/timelog.py

- Add endpoint and corresponding service method
Close #694

Add DELETE endpoint for tasks

---

frontend/src/app/providers.tsx
frontend/src/app/tasks/TaskForm.tsx
frontend/src/app/tasks/__tests__/TaskForm.test.tsx
frontend/src/app/tasks/hooks/useTask.ts
frontend/src/app/tasks/hooks/useTaskForm.ts
frontend/src/app/user/hooks/useCurrentUser.ts
frontend/src/domain/Task.ts
frontend/src/hooks/useForm/useForm.ts
frontend/src/ui/Alert/Alert.tsx
frontend/src/ui/Alert/AlertProvider.tsx
frontend/src/ui/Alert/useAlert.ts
frontend/src/ui/BaseLayout/BaseLayout.tsx
frontend/src/ui/Select/Select.tsx

This PR creates the Task Form submission, and adds an Alert component to indicate if the an action is successful or not.
1. Go to `/web/v2/tasks`
2. Select a project
3. Select the time
4. Fill other fields (optional)
5. Click `Save`
6. The form should submit and a Success or Error alert should appear
7. Pressing Ctrl+S should do the same action as clicking Save
8. The Alert should close after 15s
9. Clicking `Close` also should close the alert
[Screencast from 2023-10-11 17-09-50.webm](https://github.com/Igalia/phpreport/assets/20492786/ecd78e66-d5cc-42e9-b7b0-bb2f84cad102)

Add Task Form Submission

---

api/helpers/time.py
api/models/timelog.py
api/routers/v1/timelog.py
api/schemas/timelog.py
api/services/timelog.py
api/tests/routers/v1/test_timelog.py
api/tests/utils/mock_data.py

- minor fixes detected in the get templates endpoint
- add a couple of tests for get templates endpoint
Depends on https://github.com/Igalia/phpreport/pull/708

Add template tests and fixes

---

api/routers/v1/timelog.py
api/schemas/timelog.py
api/services/timelog.py
api/tests/routers/v1/test_timelog.py
api/tests/utils/mock_data.py

- minor fixes in the task schemas
- add tests for GET, CREATE, PUT and DELETE endpoints

Add set of tests for Tasks endpoints

---

frontend/package.json
frontend/src/app/tasks/__tests__/TaskForm.test.tsx
frontend/src/app/tasks/hooks/useTask.ts
frontend/src/app/tasks/hooks/useTaskForm.ts
frontend/src/domain/Task.ts
frontend/src/domain/__tests__/Task.test.ts
frontend/src/infra/task/createTask.ts
frontend/src/infra/task/getTasks.ts

Adds overlap check to the task form, if a task is overlapping with another it won't submit the form.
[Screencast from 2023-11-08 18-03-44.webm](https://github.com/Igalia/phpreport/assets/20492786/67c8d419-0377-4db9-8deb-e8bf90cee555)

Add task overlap check

---

frontend/src/app/tasks/TaskForm.tsx
frontend/src/app/tasks/TaskList.tsx
frontend/src/app/tasks/__tests__/TaskList.test.tsx
frontend/src/app/tasks/hooks/useTask.ts
frontend/src/app/tasks/page.tsx

Create the task listing on `/tasks` page

Create task listing

---

frontend/src/app/tasks/TaskList.tsx
frontend/src/app/tasks/__tests__/TaskList.test.tsx
frontend/src/app/tasks/components/Task.tsx
frontend/src/app/tasks/hooks/useTask.ts
frontend/src/infra/task/deleteTask.ts
frontend/src/ui/ConfirmationModal/ConfirmationModal.tsx
frontend/src/ui/ConfirmationModal/__tests__/ConfirmationModal.test.tsx

Clicking on the trashcan icon will call the task deletion endpoin
[Screencast from 2023-11-14 13-18-43.webm](https://github.com/Igalia/phpreport/assets/20492786/9a95a1b3-88cc-428e-88fb-effaaeef8b90)

Add task deletion to task list

---

frontend/src/app/tasks/__tests__/TaskForm.test.tsx
frontend/src/domain/Project.ts

The type was written with snake_case but it should be camelCase to fit with the project patterns

Fix Project type

---

frontend/src/app/tasks/TaskForm.tsx
frontend/src/app/tasks/TaskList.tsx
frontend/src/app/tasks/__tests__/TaskForm.test.tsx
frontend/src/app/tasks/components/Task.tsx
frontend/src/app/tasks/hooks/useTaskForm.ts
frontend/src/app/tasks/page.tsx
frontend/src/app/tasks/utils/time.ts
frontend/src/domain/Template.ts
frontend/src/infra/template/getTemplates.ts

This PR adds the first steps to have the template selection on the TaskForm.
It adds the template select, move the start timer button to the top and make the Logged Time box show the time difference between the startTime and endTime.

Create top bar on TaskForm

---

web/services/loginService.php

In order to parse special characters and properly build the query params for the auth http request.

Use http_build_query to build for the auth params

---

frontend/.env.example
frontend/next.config.js
frontend/src/app/api/auth/[...nextauth]/route.ts
frontend/src/app/page.tsx
frontend/src/app/providers.tsx
frontend/src/middleware.ts

THis PR removes the `/web/v2` path and it makes the `/tasks` path the default for `/`

Refine frontend path

---

frontend/package-lock.json
frontend/package.json
frontend/src/app/tasks/__tests__/components/CreateTask.test.tsx
frontend/src/app/tasks/__tests__/components/EditTask.test.tsx
frontend/src/app/tasks/components/CreateTask.tsx
frontend/src/app/tasks/components/EditTask.tsx
frontend/src/app/tasks/hooks/useCreateTaskForm.ts
frontend/src/app/tasks/hooks/useEditTaskForm.ts
frontend/src/domain/Task.ts
frontend/src/ui/Select/Select.tsx
frontend/src/ui/Select/__tests__/MaskedSelect.test.tsx

This PR moves all selects (except for the masked selects for the time picker) to use JoyUI autocomplete.

Rollback to JoyUI autocomplete

---

api/dependencies.py
api/schemas/user.py

- Add missing user_id property to schema
- Fix capacity type
- Rename property in dependencies

api: Add new property to schema

---

frontend/src/app/tasks/DayView.tsx
frontend/src/app/tasks/__tests__/components/TaskBox.test.tsx
frontend/src/app/tasks/components/DeleteTask.tsx
frontend/src/app/tasks/components/IconButton.tsx
frontend/src/app/tasks/components/SaveTemplateModal.tsx
frontend/src/app/tasks/components/TaskBox.tsx
frontend/src/app/tasks/hooks/useCreateTask.ts
frontend/src/app/tasks/hooks/useGetTasks.ts
frontend/src/app/tasks/layout.tsx
frontend/src/app/tasks/utils/time.ts
frontend/src/app/tasks/week/page.tsx
frontend/src/infra/task/getTasks.ts
frontend/src/ui/BaseLayout/BaseLayout.tsx
frontend/src/ui/Sidebar/Sidebar.tsx

Create week view

---

frontend/src/app/tasks/actions/getTasksGroupedByDate.ts
frontend/src/app/tasks/month/page.tsx
frontend/src/app/tasks/week/page.tsx
frontend/src/infra/task/getTasks.ts

This PR adds the Month view to /tasks
Desktop:
Mobile:

Create month view

---

model/facade/action/GetHolidaySummaryReportAction.php

Use the correct value for used hours

Fix percentage column in vacation summary

---

model/facade/action/SyncCalendarAction.php

Comparing the dates with different formats was unreliable and not working well, so convert the date before comparing.

Fix calendar sync
