Igalia/phpreport

web/services/loginService.php

The extra check for emtpy username and password will make sure that
the dialog is asked again in case the user enter empty string.

[#223] Force HTTP Authentication for login service

---

web/js/tasks.js

This is a rude way of fixing the bug, but the right id seems not to
load when the 'New Task' is clicked before page load

[#225] Wait till all tasks have loaded before adding in the new task

---

config/permissions.php
web/include/sidebar.php
web/js/projectDetails.js
web/projectDetails.php

Added in the top menu as requested in the bug, and now takes the user to a new page with entire project details!

[#241] Add 'Project Details' to top  menu entry

---

web/js/projectDetails.js

shifted from 350 to 440, keeping the 120 width difference between the panel and combo box borders intact.

[#266] Make Project input wider on project details page

---

web/js/tasks.js

Wait for the page to load, and then adds in a new empty task, if needed.

[#247] Open empty days with a new, empty task

---

web/js/tasks.js

Also show the `Status: New empty task created for editing` after creating a new empty task! Fix #247

[#247] Improve the 'fresh-empty-task' on a new day functionality 

---

web/js/tasks.js

> (04:49:22  IST) mrobinson: tthomas: I had a suggestion for the "empty task on empty day" feature.
(04:49:35  IST) mrobinson: tthomas: Essentially make it inactive until you click on it.
(04:49:53  IST) mrobinson: tthomas: That way you won't get a lot of dialog boxes when you are clicking through empty days.

Do not show close confirmation when its just the empty task on screen

---

sql/update/force-non-empty-project.sql
web/js/tasks.js
web/services/createTasksService.php

Related: #351 
DONE:
* Frontend: the web UI shouldn't send tasks for save before the project field is set.
* Backend: tasks without a project shouldn't be saved. This affects third-party apps using the web services.
* forbid null entries in the projectid field of a task row.
* set a default value for the previous entered tasks during the upgrade
* if, there is tasks with no project assigned -> create a default "empty" project and assing the task to this project

[#351] dont allow to save tasks without an assigned project

---

web/js/projectDetails.js
web/projectDetails.php

* Defined the 'user' variable in the scope of the web/js/projectDetails.js JS
code
* Modified the default behavior of the 'Project' combobox in
projectDetails.php to: show only the active projects for the logged user
* Added 'Load all active projects' entry in the 'Project' combobox in
projectDetails.php
* Added 'Load all projects' entry in the 'Project' combobox in
projectDetails.php
Make references to the #318 issue.

I318 Only list active projects in project details combo by default

---

web/js/include/sessionTracker.js

The relogin modal dialog reloads the page instead of perform a redirection to the login page. If there is not a valid session the user will be finally redirected to the login page but passing the current loaded URL as parameter to come back again after the login success.
Refers to #326

I326 Redirect to original URL after successful login

---

model/dao/ConfigDAO/ConfigDAO.php
model/dao/ConfigDAO/PostgreSQLConfigDAO.php
model/facade/TasksFacade.php
model/facade/action/GetTaskBlockConfigurationAction.php
model/facade/action/SetTaskBlockConfigurationAction.php
sql/update/add-date-block-to-config.sql
sql/update/all.sql
web/settings.php

Fixes #345.
Adds new fields to the database, means to retrieve and save their values from the frontend and reimplement `ConfigDAO::isWriteAllowedForDate` to take into account both a date and a number of days to block tasks.
Feedback is appreciated, specially on how to name the related fields to prevent confusion.

Lock tasks before date

---

web/js/include/sessionTracker.js

I've been testing this on my local deployment.
Adding the `success` action is hiding the MessageBox in case it exists.

Added success block to hide MessageBox in case it exists

---

config/config.php
web/viewWorkingHoursResultsReport.php

Implements a color scheme for the accumulated hours report as described in the ticket #356.
About the patches, I have doubts about the configuration value. I implemented it as a value in `config.php`, but maybe it should be in the config table of the DB and have a UI to modify it?
Fixes #356.

Change color scheme in accumulated hours report

---

web/services/getPersonalSummaryByDateService.php

There was a precision leak due to the way we've been doing the calculations when translating into days hours:minutes.

Refactored the calculations made at formatHours function

---

web/js/tasks.js

We've been adding information to the left panel. This has been putting pressure to the vertical available space. With the changes on this PR we save some of this space by doing:
* Decreased top and bottom padding at the User Work Summary
* Rearranged new and save buttons into one row layout
* Rearranged collapse and expand buttons into onw row layout

Vertical space saving on the left panel

---

web/js/tasks.js

This way, we are saving more vertical space.
Changes:
* Added a new section at the actions box
* Changed layout into an hbox
* Adjusted width and margins of both elements
* Shortened button text

Moved copy tasks from date to the actions box

---

web/js/tasks.js

`startDay` attribute was removed just because it's unnecessary.
Fix #259.

Disable "copy tasks from date" feature in blocked dates.

---

web/js/tasks.js
web/tasks.php

On a new user's first day, `$lastTaskDate` is null and is initialized to "the day before", this initialization had the side effect of modifying the original `$date` object, so any date-related checks that happened after that point were inadvertently using the previous day.
Additionally, changed behavior of default "full day" templates so they don't create any task in case the journey for that date is zero. Please check if you agree with this change of behavior.
Fixes #353.

Fix wrong length of "full day task" on new users' first day.

---

config/config.php
config/config.template
model/dao/BaseDAO.php
model/dao/BaseRelationshipDAO.php
util/LoginManager.php
web/login.php

Add two configuration parameters to integrate with external authentication services. They will:
* Bypass password check, relying on the authentication service. PhpReport doesn't need to store passwords in this case. Use with caution!
* Use a different HTTP header to check for the authenticated user name.

Integrate with external authentication

---

jobs/sendEmailAlertNoFill.php
jobs/sendEmailSummaryNoFill.php
model/dao/JourneyHistoryDAO/PostgreSQLJourneyHistoryDAO.php

Check contract start date for users without any tasks in the system, and exclude users who aren't currently contracted.
Fixes #455.

Take into account contract info in unfilled task reminders

---

web/js/userTasksReport.js

Dates were received from the server in Y-m-d format, which assumes the UTC time zone and the time 0:00 ([reference](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse#Differences_in_assumed_time_zone)). When translated to local time in areas west of the UTC, they became one day less and, for that reason, dates displayed were wrong.
Worked around the problem by using a different date format without these implications.
Fix #459.

Fix date displayed in user tasks report

---

model/facade/action/GetPendingHolidayHoursAction.php

It was a regression caused by the rename of some local variables in commit b5937a1.
Fixes #464.

Fix holiday count in leap years

---

model/facade/action/GetPendingHolidayHoursAction.php
web/js/viewWorkingHoursResultsReport.js

Future contract periods within the same year of the report are now included in the calculations.
Fixes #462.

Use future contract data to calculate pending holidays

---

web/services/getPersonalSummaryByDateService.php

In the case there were multiple contracts (journeys) between the start of the year and the date in course, the code couldn't decide which one to use and it resorted to 8 by default. To fix this, we made the query more specific, setting the current date as both start and end values.
Also, do not use 8 as the fallback journey value so, in case the user doesn't have a contract set in that moment, it reports values in HH:mm format and doesn't attempt to convert it to days.
Fixes #472.

Use correct journey value to calculate pending holidays

---

web/js/include/DateIntervalForm.js

Adds previous week, next week and last month buttons to the date filter.
It would need some work to fit the buttons on screen, at the moment the buttons that don't fit fall into an "overflow" submenu.
Fixes #477 and #478.

New buttons for date filter

---

config/config.php
web/include/menubar.php

Added ISSUE_TRACKER_LINKS_URL and ISSUE_TRACKER_LINKS_TEXT to config.php, which allow adding links to the menu with custom text.
Fixes #482.

Add configuration to link an issue tracker from the menu

---

web/js/projectDetailsReport.js
web/js/userTasksReport.js
web/js/viewWorkingHoursResultsReport.js
web/services/getExtraHoursReportService.php
web/services/getPendingHolidayHoursService.php
web/services/getProjectUserWeeklyHoursReportJsonService.php
web/services/getTasksFiltered.php

Implement server-side CSV export for the following reports:
* accumulated hours
* weekly project hours
* user tasks
Enhancements to backend code were done if possible.
Implements #475, but there are some reports left.

Server-side CSV export for some reports

---

Makefile
docs/developer/devel-setup.rst

Version 2 of UglifyJS seems to have been removed from most distros, and version 3 CLI is not backwards compatible so we need changes in the Makefile.

Change `make minify` to use the UglifyJS 3 sytax.

---

docs/admin/installation.rst
model/dao/TaskDAO/PostgreSQLTaskDAO.php
model/facade/action/PartialUpdateTasksAction.php

Improve locked date management in task updates

---

web/js/tasks.js

When we click on "today" in the calendar, we are sent to `tasks.php` with no GET parameters, but that's not the case if we use the left/right hotkeys to reach the current date.
Related: #411.

Prevent redundant GET params when using prev/next date hotkeys

---

model/vo/JourneyHistoryVO.php
tests/model/vo/JourneyHistoryVOTest.php

This method checks if a given date is between the init and end dates of a journey.
It will be used to find what journey a user had in the date of a specific task.
@jaragunde I thought of adding this "utility" methods next to their VO classes, let me know if you think they should be somewhere else.

Add dateBelongsToJourney method to JourneyHistoryVO

---

model/dao/BelongsDAO/LDAPBelongsDAO.php

This is a regression caused by commit 981533e62f1e83dbd68cd80dc215385c37d86c90.
The function `LDAPBelongsDAO->setAValues` may be called from `BaseRelationshipDAO->executeFromB`, so it's not true that it never receives the id and password fields.
Restored the original code in `LDAPBelongsDAO->setAValues`, and fixed the PHP warning that we wanted to address in a different way.

Fix regression in accumulated hours report with LDAP enabled.

---

model/facade/action/GetPersonalSummaryByLoginDateAction.php

If the week in case is the last week of the year, this method would fail because weeksTillEndOfJourneyPeriod is 0, causing a division by 0 exception.

Fix weekly goal calc if in last week of the year

---

config/permissions.php
model/facade/ProjectsFacade.php
tests/web/services/HolidayServiceTest.php
web/holidayManagement.php
web/include/phpreport.css
web/js/holidayManagement.js
web/services/HolidayService.php
web/services/updateHolidays.php

Use the same view that displays the holidays yearly to allow the user to add and edit existing holidays.
Given an array of days:
1 - delete the vacation days that are not in the list but were booked previously by the user.
2 - create new holiday tasks from the array that weren't booked yet.
Note: Holidays selected in weekends are ignored, holidays that don't belong to any journey are also ignored (for instance, trying to book a holiday in a date previous to when the person joined the company).
Next steps of the implementation:
- distinguish half leave from full day holidays visually
- display more information in the sidebar
- display success/failure messages after saving
Part of #510
Example:
- saving valid holidays and then trying to save holidays in a period before the user joined the …

Implement holiday editing methods

---

web/js/tasks.js

Display the same details that exist in the holidays view in the User Work Summary at the tasks page.

Add more details to holidays summary

---

model/facade/UsersFacade.php
model/facade/action/GetHolidayHoursBaseAction.php
model/facade/action/GetHolidayHoursSummaryAction.php
web/holidayManagement.php
web/js/holidayManagement.js
web/services/getPersonalSummaryByDateService.php

Especially by the end and beginning of the year, is useful to be
able to see close months from the past or next year so display
the holidays since July from past year until March of the
next year.
Needs https://github.com/Igalia/phpreport/pull/531 to be merged first.

Increase the number of months available in the calendar

---

docs/admin/installation.rst
model/dao/TemplateDAO/PostgreSQLTemplateDAO.php
model/vo/TemplateVO.php

First steps towards adopting PDO (#513), starting with an isolated data type that's not used a lot.

Port Template DAO to use PDO

---

composer.json
composer.lock
config/config.php
config/config.template
config/permissions.php
jobs/sendEmailAlertNoFill.php
model/facade/CalDAVCalendarFacade.php
model/facade/action/SyncCalendarAction.php
web/holidayManagement.php
web/include/calendar.css
web/include/phpreport.css
web/js/holidayManagement.js
web/services/HolidayService.php
web/services/syncCalendar.php

Adds a button in the calendar view that allows the user to sync their PhpReport holidays with a CalDav Calendar.
To test and deploy this one it will be needed to run `composer install` again since we added an external [package](https://packagist.org/packages/thecsea/simple-caldav-client) to handle the CalDav requests.
There are also a few new config variables that need to be filled in order for it to work:
```
define('CALENDAR_URL', '');
define('CALENDAR_ID', '');
define('CALENDAR_USERNAME', '');
define('CALENDAR_PASSWORD', '');
define('COMPANY_DOMAIN', '');
```

Sync PhpReport holidays with CalDav Calendar

---

model/dao/BaseDAO.php
model/dao/ConfigDAO/ConfigDAO.php
model/dao/ConfigDAO/PostgreSQLConfigDAO.php
model/dao/TemplateDAO/PostgreSQLTemplateDAO.php
util/DatabaseConnectionManager.php

This does some refactoring to reuse the PDO connection object and ports another DAO, ConfigDAO, to use this API.
Part of #513.

Port Settings DAO to use PDO

---

model/facade/UsersFacade.php
model/facade/action/GetAllActiveUsersAction.php
web/js/holidayManagement.js
web/services/getAllUsersService.php

List only users that belong to `ALL_USERS_GROUP`. This means that
they are active in the company and therefore this will hide inactive users.
Fixes https://github.com/Igalia/phpreport/issues/542

Filter active users in the Team calendar

---

tests/web/services/HolidayServiceTest.php
web/services/HolidayService.php

Instead of counting as a full day every day that has a leave,
proportionate when there are partial leaves in the week.
This was causing some confusion because the sum was always
considering each day that had a leave as 1 and creating
unprecise numbers.
Note that one day is the user journey at the time the page was
rendered.
Fixes https://github.com/Igalia/phpreport/issues/543

Consider partial leaves when grouping by week

---

model/facade/action/PartialUpdateTasksAction.php

In case there was no task for the specified ID, the code would break. Now we check if it exists before actually using the returning object.

Fix null access to $oldTask.

---

web/holidaySummary.php
web/include/report.css
web/js/holidaySummary.js
web/services/getProjectsService.php

In the production env, it may take some time to load all the projects, so it's better to show the user the data is being loaded instead of just showing a blank dropdown.

Add loading status to project list filter

---

model/facade/action/GetHolidaySummaryReportAction.php
web/holidaySummary.php
web/js/holidaySummary.js
web/services/getHolidaySummary.php

As per requests from users:
- add used column based on the date the report is generated
- reorder columns
- rename Planning to Scheduled to match the User Summary labels

Vacation Summary: Add Used column

---

web/viewUsers.php

Some little tweaks to make this screen more pleasant to use:
* Move the recently added filter into the toolbar, which is less ugly.
* When users select a name from the filter, the corresponding row will be selected.
* The grid at the bottom will be expanded when a user is selected.
* The order of the panels was changed to better reflect their use.

Improve usability of user management screen

---

web/js/holidayManagement.js

Improve the display of partial vacation days. "Leave" is a broader
category of PTO than "vacation," so using "vacation" here adds
some clarity.

Improve partial days text in vacation managementt

---

web/projectDetailsReport.php
web/projectManagement.php
web/services/createAreasService.php
web/services/createCustomersService.php
web/services/createSectorsService.php
web/services/getUserCustomersService.php
web/services/updateAreasService.php
web/services/updateCustomersService.php
web/services/updateSectorsService.php
web/viewUsers.php

Properly escape project, area, sector and customer names and other string data entered by users, in the XML and JS we generate.
Fixes #564.

Properly escape user-entered string data

---

model/dao/TaskDAO/PostgreSQLTaskDAO.php
model/dao/TaskDAO/TaskDAO.php
model/facade/action/GetScheduledHolidaysAction.php

I started fixing a PHP warning and ended doing a bit of refactoring and optimization.
I extracted the code that calculates the vacations project id to its own function and reused it from `getVacations` and `getVacationsDates`. This also has the advantage of reducing the usage of the `VACATIONS_PROJECT` config parameter in case we want to get rid of it. We also cache the value for subsequent calls, it's useful for `getVacations` which we call several times in the same request.

Enhance how we fetch the vacations project id

---

web/projectsEvaluation.php

We need to use json_encode to properly escape user-entered names in generated JS code, which might contain special characters.
This is the same problem we fixed already for other pages. I hadn't realized it affected the project evaluation report too, which we use less often.
Fixes #564.

Escape area names in project evaluation report.

---

web/js/include/ExportableGridPanel.js

Data URLs generated by the legacy CSV exporter wasn't working
anymore. The workarround to fix it is creating a temporary anchor
element, attach the data to it and simulate a click to download it.
Tested in Chrome, FF and Safari.

Fix Download as CSV button

---

config/config.php
model/dao/TaskDAO/PostgreSQLTaskDAO.php
model/dao/TaskDAO/TaskDAO.php
model/facade/TasksFacade.php
web/services/HolidayService.php
web/tasks.php

Create a new parameter, VACATIONS_PROJECT_ID, and add a migration path where the old parameter will still work if the new is not set.

Deprecate VACATIONS_PROJECT config parameter

---

Makefile

This will enforce browsers to retrieve again the file when the hash changes, making sure users don't use old versions of the JS code.
The minify script is changed in several ways, in addition to calculating and appending the hash to the file name:
* To revert previous minification, we now use git reset --hard. It's   dangerous but prevents the regexp logic from getting too wild.
* We now loop through the php files for every js file, making the script much less efficient. Again, this is done to simplify regexp  logic.
* Explicitly delete source map files from previous minification, to prevent maps with different hashes to pile up.
Fixes #439.

[#439] Append a hash to minified file names.

---

Makefile
web/holidayManagement.php

This was not being minified because the regexp didn't match.
We also tune a bit the `find` commands, to reduce the search scope.

Properly minify holidayManagement.js.

---

Makefile
docs/developer/devel-setup.rst

Disable `-c` parameter in UglifyJS to prevent the error. This increases the output size, but only slightly (from ~700 KB to ~800 in tasks page).
Also write down the minimum UglifyJS version number known to prevent problems with the most modern JS syntax features.
Fixes #585.

Workaround for minification error in tasks page.

---

model/dao/TaskDAO/PostgreSQLTaskDAO.php
model/dao/TaskDAO/TaskDAO.php
model/vo/TaskVO.php
sql/update/add-updated-at-to-task.sql
sql/update/all.sql
sql/update/bump-db-version-2-22.sql
update/update-from-2.21-to-2.22.php

We need to know when users update their tasks, specially the ones related to their vacation plans.
This patch adds a column called `updated_at` to the task table as well as their migration scripts.
It also starts populating the field whenever a task is created or updated.

Add updated_at field to task

---

docs/user/tasks.rst
web/js/tasks.js

The hotkeys ctrl+number are used in Chrome (and Edge) to switch tabs.
Related to #164.

Use alt+shift+number to switch tasks.

---

model/facade/action/PartialUpdateTasksAction.php
web/include/validations.js
web/js/tasks.js
web/services/createTasksService.php

Some users need to record 0-hour tasks to record when they work
or took the day off but don't want to affect the amount of worked hours.

Allow 0 hour tasks

---

model/OperationResult.php
model/dao/ProjectDAO/PostgreSQLProjectDAO.php
model/dao/ProjectDAO/ProjectDAO.php
model/facade/ProjectsFacade.php
model/facade/action/CreateProjectAction.php
web/js/projectManagement.js
web/services/createProjectsService.php

This PR begins to address #496 by adding an OperationResult class and updates code related to the creation of Projects to begin using this class. Changes in these commits include:
- Add the OperationResult class
- Refactor Project DAO and Facade to use this class
- Update createProjectsService to check class
- Update projectManagement.js exception handler for project creation to pass along the message from the back end.
Comments and suggestions welcome as my PHP is a bit rusty.

Add OperationResult class and begin handling sql errors more gracefully

---

web/services/createTasksService.php
web/services/updateTasksService.php

Fixes #611 
I removed the check against `$initTime` out of the parser switch statement for the `$endTime` block since values are set in the order the user set them, which could cause errors due to variables/values not being set yet. I instead make the check after the switch block is done.

611 midnight task error

---

model/dao/TaskDAO/PostgreSQLTaskDAO.php

We check for "not null violation" error messages from PostgreSQL and turn them into a more user friendly message: "Missing compulsory data". We add a specific check and message for missing init and end time fields which are the only ones that realistically can happen at that point; missing project and user fields should have been checked in upper layers.
This fixes an old bug, #110, together with the recent work to turn SQL exceptions into error messages.

Error message for missing compulsory fields on task create.

---

model/dao/TaskDAO/PostgreSQLTaskDAO.php
model/dao/TaskDAO/TaskDAO.php
model/facade/TasksFacade.php
model/facade/action/CreateTasksAction.php
model/facade/action/DeleteReportAction.php
model/facade/action/PartialUpdateTasksAction.php
web/include/App.js
web/include/phpreport.css
web/services/createTasksService.php
web/services/deleteTasksService.php
web/services/updateTasksService.php

I'm increasing the error reporting for task update and delete operations, and also making some changes in the front-end to make error messages more noticeable; I'm afraid that users have become accustomed to ignore them.

Report detailed error messages on task update and delete

---

model/dao/BelongsDAO/PostgreSQLBelongsDAO.php
model/dao/UserDAO/HybridUserDAO.php
model/dao/UserDAO/PostgreSQLUserDAO.php
model/dao/UserDAO/UserDAO.php
model/facade/UsersFacade.php
model/facade/action/CreateUserAction.php
model/facade/action/DeleteUserAction.php
model/facade/action/UpdateUserAction.php
web/services/createUsersService.php
web/services/deleteUsersService.php
web/services/updateUsersService.php
web/viewUsers.php

This affects the Postgres and LDAP DAOs. Notice there are many operations in the user management screen (assign users to groups and all the user history assignment) that aren't upgraded yet to OperationResult and they keep working as usual.

Report better errors on user CRUD operations

---

.github/workflows/runtests.yml
composer.json
composer.lock
docker/docker-compose.test.yml
docker/test.app.Dockerfile
docs/developer/devel-setup.rst
tests/integration/LoginServiceTest.php
tests/integration/LoginSetupTestCase.php
tests/integration/TaskServiceTest.php
web/services/createTasksService.php

Finally add support for integration tests using docker so we can now test all the service layer without having to change anything in the application design.
The unit tests will work locally without issues, but the integration tests will only work if there is a service running on the port 8000 with the data from the `sql/initialData.sql` file. In that case it's easier to run it with docker, as it has everything setup.
In one terminal build and run the application and the database:
``docker-compose -f docker/docker-compose.test.yml up --build --renew-anon-volumes``
In a second terminal run the ``test`` container to run the tests:
``docker-compose -f docker/docker-compose.test.yml run -T test``
---
I've also added a few tests that check the loginService and task creation.

Add support for integration tests and a small set of tests

---

web/js/tasks.js

Some users are experiencing some friction/confusion when adding/editing tasks. Specifically, the "detected overlapping times" error alert will pop up intermittently even when task times do not overlap. It's hard to reproduce, but the best @anarute and I can figure is that there is dirty/incomplete data passed along during the auto-save that is possibly causing this error. 
This small code change - increasing the auto-save interval from 10s to 30s - would help in the short-term. Thirty seconds is still a short interval while being long enough to allow for a user to settle task times before the auto-save is engaged.

Increase autosave interval for tasks

---

jobs/sendEmailAlertNoFill.php
jobs/sendEmailSummaryNoFill.php

The script was checking if the user had a journey or not, so if a user joined the current week they would receive a reminder because they are active but haven't filled the past week.
This patch checks if the user joined at least a week ago and for the summary email, also checks if they were active in the previous weeks too before adding them to the lists.

Make sure not to send email to new joiners

---

web/js/tasks.js

It is very easy to accidentally delete a template. The code here puts a confirmation modal in place so that a user has an escape hatch if they accidentally click the 'delete' button for a template they actually want to keep.

Add confirmation modal when deleting template

---

web/js/userTasksReport.js

If someone has added an html element/tag inside their task description, the html gets rendered in the User Tasks report. In order to prevent this, I have added a small renderer function that uses one of Ext.js' native utils - an htmlEncoder. 
To test:
- Add a task with something like the following in the description: "Worked on adding support for <iframe> in XYZ repository"
- Save task
- Under 'Reports', choose 'User tasks'
- Select a date range that encompasses the task you just added
- Check to see if '<iframe>' is simply rendered as the element as text or if there is a blank iframe in the 'Description' column

Add column renderer to handle html in description

---

web/js/areaManagement.js
web/js/customerManagement.js
web/viewUsers.php

Records added via the inline edit grids also prefill info and this can be a speedbump since users then have to delete the prefilled text in order to enter their own text. Instead, I propose leveraging the `emptyText` property in the editor which will add placeholder text that a user wouldn't have to delete.
Leaving this as draft for the moment so that folks can try it out to see if they agree with the new approach.

Leave new records empty rather than prefill

---

model/dao/ProjectDAO/PostgreSQLProjectDAO.php
model/vo/CustomProjectVO.php
model/vo/ProjectVO.php
web/js/projectDetailsReport.js
web/projectDetailsReport.php

Sometimes users can mistakenly log hours in the future and this was causing confusion because the total hours vs the hours displayed per user in the report didn't match.
With this patch, if a project has hours logged in the future a field with the amount of hours will be displayed in red in the project details report.

Display if project has hours logged in the future

---

web/js/tasks.js

- Need to multiply hours by 60 to get total of minutes else evaluation of overlap can be wrong

Fix calculation of total minutes for overlapping tasks

---

model/dao/DAOFactory.php
util/ConfigurationParametersManager.php
web/services/getUserStoryReportJsonService.php

- The env file was being loaded on every request, making the application slower.
- The custom DAO logic wasn't being used and only added complexity and unnecessary
checks on every request.

Improve how to get env file and deprecate custom DAOs

---

web/js/tasks.js

The check for tasks overlap function fails when copying tasks from another day, so we need to check for the existence of the property before filtering.

Add check for property before trying to filter on it

---

web/login.php

Solves: PhpReport login page should redirect if already logged in #494
What i did:
Added a logic check in login.php to check if LoginManager.isLogged is not returning null. 
If null is not returned then the the user is redirected to tasks.php

fix login page redirect if already logged in

---

web/js/include/sessionTracker.js

The user is logged out only if the user wasn't found and therefore checkSessionActive.php returns 401. Other failures are probably transient or something that has nothing to do with the login.

Ask to relogin only if response is 401

---

api/schemas/project.py

The notation X | Y only works for python 3.10+

Fix type annotation for python 3.9

---

.dockerignore

They are needed in order to run the apps - it was working in some cases where the dev had run composer install or npm install manually.

Remove vendor folders from dockerignore

---

api/migrations/versions/39723f474338_add_column_to_template_table.py
api/models/timelog.py
api/routers/v1/timelog.py
api/schemas/timelog.py
api/services/timelog.py

First, there are some small changes to the `template` table to allow for storage of global templates in the database.
Second, this adds a GET endpoint to the API to retriever user templates. This will get all templates the user has created as well as all global templates.

Add template endpoint

---

api/migrations/versions/217cb64b0391_initial_db_creation.py
api/models/user.py
docker/docker-compose.dev.yml
docs/src/developer/devel-setup.md
sql/initialData.sql

Several improvements on how we can setup the development environment using docker and a clean database.

Improve initial setup

---

api/models/project.py
api/routers/v1/projects.py
api/schemas/project.py
api/services/projects.py

- Implement projects basic pagination with offset and limit query params
- Add project status filter that allows the user to filter for active and inactive projects, if there's no filter all the projects will be returned.

Add pagination and filter to the projects endpoint

---

api/models/project.py
api/models/timelog.py
api/routers/v1/timelog.py
api/schemas/customer.py
api/schemas/timelog.py
api/services/timelog.py

- Add schemas for task and customer
- Add method to timelog service for fetching tasks
- Modify models for project and task as needed
These changes implement a basic GET endpoint for user tasks. As the amount of tasks fetched could grow to be very large, I have added both offset/limit and date range query params so that the frontend consumer is not overwhelmed with data.

Implement get_user_tasks endpoint

---

api/db/db_connection.py
api/models/timelog.py
api/routers/v1/timelog.py
api/schemas/timelog.py
api/services/timelog.py

Closes #676
The changes here add the necessary schema, service methods, and endpoint for the creation of templates.
- Db connection updated so expire on commit is false. This prevents errors when trying to refresh the object for return to the api from service
- User model imported in timelog model explicitly. This solves occasional 'NoneType' error being thrown. I think it is due to the fact that we have foreign keys to user, which has a model defined in a separate file.
- Add template schema. Includes validation for column size, as well as check for is_global and user_id.
- Add template endpoint. Also add a 404 as a potential response type for the router.
- Add service to create template
Notes: For the schemas, I used the full-stack-fastapi-postgresql as a loose guide. Shared properties …

Add POST endpoint for templates

---

api/dependencies.py
api/helpers/time.py
api/models/timelog.py
api/pyproject.toml
api/routers/v1/timelog.py
api/schemas/customer.py
api/schemas/project.py
api/schemas/timelog.py
api/schemas/user.py
api/services/config.py
api/services/projects.py
api/services/timelog.py

Closes #677 
- Update Pydantic to v2 and make associated syntax changes to several models
- Add validation, computed fields, and hybrid properties to support task creation
- Add services and service methods to validate tasks
- Add/update schemas for tasks

Add POST task endpoint

---

frontend/src/app/tasks/hooks/useTaskTypes.ts

This PR removes the mocked data from`useTaskTypes`

Remove mocks from taskType api fetch

---

api/routers/v1/timelog.py
api/schemas/timelog.py
api/schemas/validation.py
api/services/timelog.py

Closes #681 
- Fix regression where template model validator was lost in upgrade to Pydantic
- Add endpoint and basic checks: same user checks as for adding a template, check that template user is seeking to edit exists
- Add simple schema for update
- Add service methods to get single template and to update
- Add additional validation for templates to check if there is a task_type and if there is to make sure it exists (otherwise there is a FK error)

Add PUT template endpoint

---

api/schemas/project.py

/projects/{project_id} GET endpoint was erroring out due to a type mismatch. This commit aligns the schema property with the model.

Fix type of project id

---

api/routers/v1/timelog.py
api/schemas/timelog.py
api/services/timelog.py

Closes #692 
- Add the endpoint
- Add TemplateUpdate schema
- Add a simple get method to tasks service so we can check for existing task
- Small updates to endpoint docs to provide more clarity
- Update validation.
The validation updates for update were a bit extensive. Since it should be possible for someone to send a PUT request with only the task_id and the properties they want to update, we needed several additional checks to ensure the validation would work with a partial object. Mostly, we need to ensure the required properties (user_id, project_id, end, init, date) are on the object to be validated or else the validation fails.

Add PUT endpoint for tasks

---

README.md

I don't know how I missed the broken badge before, but this should fix.

Fix link to documentation workflow badge

---

frontend/src/app/tasks/__tests__/TaskForm.test.tsx
frontend/src/app/tasks/hooks/useTaskForm.ts

This PR adds the form submission with `Enter` key press
1. Open the form
2. Press Enter
3. It should trigger the form submit

Add form submission with Enter key

---

.gitignore
api/tox.ini

Run pytest with coverage and add a coverage report step in tox.
Next step would be adding a badge to the project, but for now I think this should be enough.

Add test coverage to the API

---

.github/workflows/runtests.yml

The frontend tests don't need to run on docker nor need the DB running so better to split them to get an easier to read output.

Split front and back tests in GH actions

---

util/LoginManager.php
web/services/loginService.php

- Make oidc client init method public so it can be used elsewhere
- Add check for use of external auth. If using, make a curl request to the token endpoint to log user in with OIDC, set access token and user.
The loginService.php is only used with the old API and it needs to bypass the OAuth provider login page and redirect. This is why the auth request here is made via curl to the token endpoint.

Patch login service

---

api/dependencies.py
api/models/user.py
api/schemas/user.py
frontend/src/domain/User.ts

This adds the 'capacities' list to the User object in front and back end. A capacity is defined here as the number of hours a user works per week for the provided timeframe. We use the capacity to do several of the calculations in the summary, so it makes sense to include it as part of the user payload.

Add user capacity to AppUser object

---

api/dependencies.py
api/schemas/customer.py
api/schemas/project.py
api/schemas/timelog.py
api/schemas/user.py
api/tests/routers/v1/test_timelog.py
api/tests/utils/mock_data.py

- Use alias generator from pydantic to emit camel case and set populate_by_name to true so validation does not fail
- Update fill of capacities list in get_current_user due to model type mismatch after update of schemas
- Update json in tests to match new schema
Regarding the second item here: prior to changing the model_config for UserCapacity, it seems that the mapping from model.user.UserCapacity => schemas.user.UserCapacity happened under the hood easily. After the change, pydantic was quite unhappy about the type mismatch, so I did a simple iterate and append. If I missed some easier way to address this, please let me know.
This was the error received after the model config change:
```
File "/usr/local/lib/python3.9/dist-packages/pydantic/main.py", line 164, in __init__
2023-11-10 …
```

Update schemas to return camel case json

---

frontend/jest.config.mjs
frontend/src/app/api/auth/[...nextauth]/route.ts
frontend/src/app/tasks/TaskForm.tsx
frontend/src/app/tasks/TaskList.tsx
frontend/src/app/tasks/__tests__/TaskForm.test.tsx
frontend/src/app/tasks/hooks/useTask.ts
frontend/src/app/tasks/hooks/useTaskForm.ts
frontend/src/app/tasks/page.tsx
frontend/src/hooks/useGetCurrentUser/useGetCurrentUser.ts
frontend/src/infra/user/getCurrentUser.ts
frontend/src/types/next-auth.d.ts

This PR creates the `useGetCurrentUser` hook, it returns the user data from the session. In the route we add the user data to the session and now it can be accessed at any client component trough this hook.

Create user session hook

---

api/alembic.ini
api/db/base.py
api/migrations/versions/dc2b619f65a9_add_archive_table_and_triggers.py
api/models/archive.py
api/pyproject.toml
docs/src/developer/devel-setup.md

- Add alembic_utils to package list
- Add necessary logging configs per alembic_utils docs
- Create migration that adds archive table, adds function that logs to table, and add trigger to project table
- Add model for archive table 
- Add information to docs on how to add a trigger to other tables that use the logging function

Add migration for archive table and trigger

---

model/facade/action/GetHolidayHoursBaseAction.php

The holiday summary for an upcoming year was improperly calculating and showing some hours as used, which should not be possible. This solution checks the referenceDate passed to the method doing the calculation and if it is in the future, the used hours are set to 0.

Fix: Set used hours to 0 if the date is in the future

---

frontend/src/hooks/useGetCurrentUser/useGetCurrentUser.ts

If session data doesn't exist, it only returns an empty object

Fix useGetCurrentUser breaking on server

---

frontend/src/app/globals.css

The select was being cropped because the <body> tag on html was shorter than the screen, now it fills the whole screen but can be expanded if necessary.

Fix select being on task form

---

util/LoginManager.php

- This check is causing too many requests to OAuth and is not necessary

Remove extra check in isLogged

---

api/routers/v1/timelog.py
api/services/timelog.py
api/tests/routers/v1/test_timelog.py
web/js/tasks.js
web/services/getTaskTypes.php

There were 2 issues in our task types dropdown:
- when typing in the field, the autocomplete was displaying inactive task types as if they were still active.
- if a user had an inactive task type saved as a template, they could still use it.
This PR adds a filter in the endpoint that allows us to get only the active task types and it adds a check to validate the task type when a user uses a template.

Fix task types dropdown

---

web/js/tasks.js

Includes only works for flat arrays, we want the method `some` in this case.

Use some instead of includes to check task types

---

api/migrations/versions/217cb64b0391_initial_db_creation.py
api/models/project.py

It should be a composed primary key of user and project, not just the user id.

Fix ProjectAssignment primary keys

---

model/facade/action/GetHolidayHoursBaseAction.php
model/facade/action/GetHolidaySummaryReportAction.php
web/holidaySummary.php
web/services/getHolidaySummary.php

- Change how we get used/scheduled hours if reference date is in the future
- Update calculation in summary report action to subtract used hours
- Rename variable to match the ui for clarity

Fix holidays calculations

---

docs/src/user/tasks.md
web/js/tasks.js

Remove load all projects feature and make sure when loading from templates the users can't log time into projects they are not assigned to.

Disallow log time to projects user is not assigned

---

frontend/src/app/tasks/components/EditTask.tsx
frontend/src/app/tasks/hooks/useCreateTaskForm.ts
frontend/src/app/tasks/hooks/useEditTaskForm.ts

Pressing Ctrl+S will try to save the current active form.
[Screencast from 2023-12-21 12-20-47.webm](https://github.com/Igalia/phpreport/assets/20492786/9027eb98-451c-438f-b8bf-886d07402816)

Add ctrl+s save to edit form

---

model/facade/action/SyncCalendarAction.php

- In order to avoid very large request sets to the calendar provider, the window here is reduced to 3 months in the past until Dec 31 of the next year.

Adjust window of events to calendar  sync

---

frontend/src/app/tasks/components/CreateTask.tsx
frontend/src/app/tasks/hooks/useCreateTaskForm.ts

The select template function wasn't setting the projectName so it left the project select empty when prefilling the form with a template.

Fix template select not selecting the project

---

api/auth/auth_handler.py

This gives a better response to the user

Raise error when token has expired

---

api/tests/utils/mock_data.py
model/dao/ProjectDAO/PostgreSQLProjectDAO.php
web/services/createTasksService.php

Instead of having to manually assign everyone to all the leave projects, return them when fetching user's projects.
Also check if they can log time to a project before creating a task.

Enable leave projects to everyone

---

frontend/src/app/api/auth/[...nextauth]/route.ts
frontend/src/app/planner/page.tsx
frontend/src/app/tasks/hooks/useDeleteTask.ts
frontend/src/app/tasks/page.tsx
frontend/src/infra/project/getProjects.ts
frontend/src/infra/task/deleteTask.ts
frontend/src/infra/taskType/getTaskTypes.ts
frontend/src/infra/template/getTemplates.ts
frontend/src/infra/user/getCurrentUser.ts

This PR changes the rest of the files in /infra to use the factory pattern:
```ts
// from
getSomething = async (apiClient: apiClient) => {}
// to
makeGetSomething = (apiClient: apiClient) => async () => {}
```
This change is to ensure that all functions that depend on an apiClient will receive the argument the same way, to make it standardized.

Refactor rest of infra

---

frontend/src/ui/Input/Input.tsx
frontend/src/ui/Input/MaskedInput.tsx
frontend/src/ui/Input/styles.tsx

The StyledInput was changed to a Box as input, this changed is to avoid having to use LegacyRef that the styled function required and a ts-ignore was added to the MixinInput, because although we are using it just as the lib docs exemplifies the ts returns an error.

Remove ts errors from masked input

---

api/helpers/time.py
api/routers/v1/timelog.py
api/schemas/timelog.py
api/services/timelog.py
api/tests/conftest.py
api/tests/helpers/test_time.py
api/tests/routers/v1/test_timelog.py
api/tests/utils/mock_data.py
frontend/src/app/tasks/components/WorkSummaryPanel.tsx
frontend/src/app/tasks/hooks/useCreateTask.ts
frontend/src/app/tasks/hooks/useDeleteTask.ts
frontend/src/app/tasks/hooks/useEditTask.ts
frontend/src/app/tasks/hooks/useWorkSummary.ts
frontend/src/app/tasks/layout.tsx
frontend/src/domain/WorkSummary.ts
frontend/src/infra/workSummary/getWorkSummary.ts
frontend/src/ui/BaseLayout/BaseLayout.tsx
frontend/src/ui/CollapseButton/CollapseButton.tsx
frontend/src/ui/ContentSidebar/ContentSidebar.tsx
frontend/src/ui/Sidebar/DarkModeSwitch.tsx
frontend/src/ui/Sidebar/Sidebar.tsx

The work summary panel will be visible only from the tasks area and show the user some basic information about the time they have worked for today and the week, as well as vacation time and extra hours. This information is shown in the current version of the application on the left side of the app. Some small improvements have been made here, such as breaking down the worked hours by project for a user and adding tooltips to explain each vacation category (used, scheduled, pending). 
A few small UI changes have been made here, as well. The collapse button for the right panel has been modified to be within the panel instead of a floating button. The dark/light mode toggle has been made smaller on the desktop view (same as it appears on mobile).
This is a first version of the component and …

Add work summary panel

---

web/js/tasks.js

This PR adds a small sort to the projects list dropdown on the Tasks page. It sorts by type (so that projects of type 'leave' are sorted after those without a type) then by name.

Sort leave projects last in tasks page dropdown

---

api/migrations/versions/6a1ad39b566d_add_calculation_functions.py
docker/prod.frontend.Dockerfile
frontend/src/infra/taskType/getTaskTypes.ts

This PR contains 2 small patches to fix errors found on deployment.
- Not specifying the port/hostname as env values in frontend image works when running locally but fails in a production environment
- Fix task type endpoint

patch: Add envs for port and host, fix endpoint

---

frontend/src/app/tasks/__tests__/components/CreateTask.test.tsx
frontend/src/app/tasks/hooks/useTaskFormTimer.ts
frontend/src/hooks/useTimer/__tests__/useTimer.test.ts
frontend/src/hooks/useTimer/useTimer.ts

This changes allow the form to maintain the timer state even after a reload or closing and reopening it.
[Screencast from 2024-01-31 14-45-18.webm](https://github.com/Igalia/phpreport/assets/20492786/c1ad91ef-dab4-4618-811e-c083457bdde6)

Add timer initial value to localStorage

---

frontend/package-lock.json
frontend/package.json
frontend/src/app/tasks/components/SaveTemplateModal.tsx
frontend/src/ui/SubmitButton/SubmitButton.tsx

This PR fix the typescript error in the SaveTemplate form.
[Screencast from 2024-02-19 15-24-59.webm](https://github.com/Igalia/phpreport/assets/20492786/af1ad60e-39c4-4a96-af88-bbeec9aff65c)

Fix create template modal

---

web/holidaySummary.php
web/js/holidaySummary.js
web/services/HolidayService.php

This adds some additional information to the table header in the holiday summary report - specifically, it adds the first day of the week. This change is made so that users won't have to look up when an ISO week starts and can then have a better idea of when leaves are happening.
Once again, some of the changes show here are from auto-formatting - sorry! 
Main change in HolidayService.php is in lines 420-426 where the new array is created that has the week ('2024W01') and the weekStartDate ('Jan 1').
Main changes in holidaySummary.js are at lines 36 and 105 where the weeksStartDate is added and filled.
Then in the holidaySummary.php, the change is at line 69 where the additional info (the week start date) is added to the table header.

Add dates to holiday summary report header

---

web/js/include/ExportableGridPanel.js
web/js/userTasksReport.js

- Revert to use regular grid panel and the download csv functionality just in this file and remove Total Hours from csv export

fix: Revert userTasksReport grid change
